# Generated by Django 4.1.7 on 2023-07-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CastoonnApp', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
