# Generated by Django 4.1.7 on 2023-07-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CastoonnApp', '0003_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
