# Generated by Django 4.1.7 on 2023-07-19 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CastoonnApp', '0005_profile_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_artist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CastoonnApp.user_registration'),
        ),
        migrations.AlterField(
            model_name='profile_artist',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile_artist',
            name='awards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile_artist',
            name='goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile_artist',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile_artist',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile_artist',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile_artist',
            name='passions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile_artist',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile_artist',
            name='social_media_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
